[package]
name = "smartclock-sim"
description = "A simulated SmartClock receiver, for testing without hardware"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
jiff = "0.2.37"
smartclock = { path = "../smartclock" }

[dev-dependencies]
jiff = "0.2.37"
