//! Generates the command table in `commands.toml` into Rust.
//!
//! Keeping the table as data means the two dialects, their per-model
//! availability and their manual citations stay diffable against the
//! documents.  Generating rather than parsing at runtime makes the
//! command id set an enum, so a typo fails to compile.

use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use serde::Deserialize;

/// One command as written in `commands.toml`.
#[derive(Deserialize)]
struct Command {
    /// Stable logical name, independent of dialect.
    id: String,
    /// `query`, `control` or `dangerous`.
    class: String,
    /// One-line description, used as the generated doc comment.
    doc: String,
    /// Per-dialect spellings, keyed by dialect name.
    dialect: BTreeMap<String, Dialect>,
}

/// How one dialect spells a command.
#[derive(Deserialize)]
struct Dialect {
    /// The SCPI string to send.
    scpi: String,
    /// Name of the parser that reads the reply.
    response: String,
    /// Receivers exposing this command in this dialect.
    models: Vec<String>,
    /// Manual and page the entry was taken from.
    cite: String,
    /// Whether the entry has been confirmed against hardware.
    verified: bool,
}

/// Top level of `commands.toml`.
#[derive(Deserialize)]
struct Table {
    schema: u32,
    command: Vec<Command>,
}

/// The schema version this build script understands.
const SCHEMA: u32 = 1;

fn variant(id: &str) -> String {
    id.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn main() {
    println!("cargo::rerun-if-changed=commands.toml");
    println!("cargo::rerun-if-changed=build.rs");

    let raw = fs::read_to_string("commands.toml").expect("read commands.toml");
    let table: Table = toml::from_str(&raw).expect("parse commands.toml");
    assert_eq!(table.schema, SCHEMA, "commands.toml schema is not {SCHEMA}");

    let dialects: BTreeSet<&str> = table
        .command
        .iter()
        .flat_map(|c| c.dialect.keys().map(String::as_str))
        .collect();

    let mut out = String::new();
    out.push_str("// Generated by build.rs from commands.toml.  Do not edit.\n\n");

    out.push_str("/// A command tree.  Receivers of one family share a tree.\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    out.push_str("pub enum Dialect {\n");
    for d in &dialects {
        let _ = writeln!(out, "    /// The `{d}` command tree.\n    {},", variant(d));
    }
    out.push_str("}\n\n");

    out.push_str("/// What a command may do, and so how it is gated.\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    out.push_str("pub enum Class {\n");
    out.push_str("    /// Read-only; always permitted.\n    Query,\n");
    out.push_str("    /// Changes receiver state; requires configuration opt-in.\n    Control,\n");
    out.push_str("    /// Can strand the link or wipe configuration.\n    Dangerous,\n");
    out.push_str("}\n\n");

    out.push_str("/// A logical operation, independent of how a dialect spells it.\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    out.push_str("pub enum CommandId {\n");
    for c in &table.command {
        let _ = writeln!(out, "    /// {}\n    {},", c.doc, variant(&c.id));
    }
    out.push_str("}\n\n");

    out.push_str("/// How one dialect spells one command.\n");
    out.push_str("#[derive(Debug, Clone, Copy)]\n");
    out.push_str("pub struct Spec {\n");
    out.push_str("    /// The logical operation.\n    pub id: CommandId,\n");
    out.push_str("    /// Gating class.\n    pub class: Class,\n");
    out.push_str("    /// The SCPI string to send.\n    pub scpi: &'static str,\n");
    out.push_str(
        "    /// Name of the parser that reads the reply.\n    pub response: &'static str,\n",
    );
    out.push_str(
        "    /// Receivers exposing this command.\n    pub models: &'static [&'static str],\n",
    );
    out.push_str("    /// Manual and page the entry came from.\n    pub cite: &'static str,\n");
    out.push_str(
        "    /// Whether it has been confirmed against hardware.\n    pub verified: bool,\n",
    );
    out.push_str("}\n\n");

    for d in &dialects {
        let entries: Vec<_> = table
            .command
            .iter()
            .filter_map(|c| c.dialect.get(*d).map(|spec| (c, spec)))
            .collect();
        let _ = writeln!(
            out,
            "/// Every command the `{d}` tree defines.\nstatic {}: [Spec; {}] = [",
            variant(d).to_uppercase(),
            entries.len()
        );
        for (c, spec) in entries {
            let class = match c.class.as_str() {
                "query" => "Query",
                "control" => "Control",
                "dangerous" => "Dangerous",
                other => panic!("unknown class {other:?} on command {:?}", c.id),
            };
            let models = spec
                .models
                .iter()
                .map(|m| format!("{m:?}"))
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(
                out,
                "    Spec {{ id: CommandId::{}, class: Class::{class}, scpi: {:?}, \
                 response: {:?}, models: &[{models}], cite: {:?}, verified: {} }},",
                variant(&c.id),
                spec.scpi,
                spec.response,
                spec.cite,
                spec.verified
            );
        }
        out.push_str("];\n\n");
    }

    out.push_str("impl Dialect {\n");
    out.push_str("    /// Every command this dialect defines.\n");
    out.push_str("    pub fn specs(self) -> &'static [Spec] {\n        match self {\n");
    for d in &dialects {
        let _ = writeln!(
            out,
            "            Dialect::{} => &{},",
            variant(d),
            variant(d).to_uppercase()
        );
    }
    out.push_str("        }\n    }\n\n");
    out.push_str("    /// How this dialect spells `id`, if it has it at all.\n");
    out.push_str("    pub fn spec(self, id: CommandId) -> Option<&'static Spec> {\n");
    out.push_str("        self.specs().iter().find(|s| s.id == id)\n    }\n}\n");

    let dest = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join("commands.rs");
    fs::write(&dest, out).expect("write generated commands");
}
